gestion_films:
    resource: "@GestionFilmsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /